import Head from "next/head";
import "./../styles/globals.css";
import { Inter } from "next/font/google";
import { Metadata, Viewport } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  themeColor: 'black',
  initialScale:1,
  maximumScale:1,
  width: "device-width",
  userScalable:false
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
     
      <body
        suppressHydrationWarning={true}
        style={{ height: "100vh" }}
        className={inter.className}
      >
        {children}
      </body>
    </html>
  );
}
